# Generated by Django 2.0 on 2019-05-24 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('student', '0004_auto_20190523_1419'),
        ('book', '0003_auto_20190523_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=20)),
                ('lost', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
