# Generated by Django 2.0 on 2019-05-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
