# Generated by Django 2.0 on 2019-05-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_borrow_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='Staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='lost',
            field=models.TextField(blank=True),
        ),
    ]
