# Generated by Django 2.0 on 2019-05-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_auto_20190524_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='quantity',
        ),
    ]
