# Generated by Django 2.0 on 2019-05-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_book_code'),
        ('borrow', '0007_remove_borrow_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='Book',
        ),
        migrations.AddField(
            model_name='borrow',
            name='Book',
            field=models.ManyToManyField(to='book.Book'),
        ),
    ]
