# Generated by Django 2.0 on 2019-05-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_book_code'),
        ('borrow', '0008_auto_20190525_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='Book',
        ),
        migrations.AddField(
            model_name='borrow',
            name='Book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book_code',
            field=models.CharField(default='book1', max_length=20, unique=True),
        ),
    ]
