# Generated by Django 2.0 on 2019-05-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190527_2209'),
        ('borrow', '0010_borrow_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='Book',
        ),
        migrations.AddField(
            model_name='borrow',
            name='Book',
            field=models.ManyToManyField(to='book.Book'),
        ),
    ]
