# Generated by Django 2.0 on 2019-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0012_auto_20190528_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book_code',
            field=models.IntegerField(default='1', max_length=20),
        ),
    ]
