# Generated by Django 2.0 on 2019-05-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0014_auto_20190531_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='lost',
            field=models.TextField(blank=True, null=True),
        ),
    ]
