# Generated by Django 2.0 on 2019-05-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0015_auto_20190531_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='quantity',
            new_name='stock',
        ),
    ]
