# Generated by Django 2.0 on 2019-06-03 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0017_auto_20190531_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='date',
            new_name='borrow_date',
        ),
        migrations.AddField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
