# Generated by Django 2.0 on 2019-05-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190523_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_code',
        ),
    ]
