# Generated by Django 2.0 on 2019-05-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_book_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quantity',
            new_name='available',
        ),
    ]
