# Generated by Django 2.0 on 2019-05-30 13:56

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190527_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=1, validators=[book.models.is_posititve]),
        ),
    ]
