# Generated by Django 2.0 on 2019-05-30 14:57

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190530_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0, validators=[book.models.is_posititve]),
        ),
    ]
