# Generated by Django 2.0 on 2019-05-30 15:04

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190530_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=models.IntegerField(default=1, validators=[book.models.is_posititve]), validators=[book.models.is_posititve]),
        ),
    ]
