# Generated by Django 2.0 on 2019-05-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20190530_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
    ]
