# Generated by Django 2.0 on 2019-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, unique=True)),
                ('lname', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
