# Generated by Django 2.0 on 2019-05-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190523_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='fullname',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
